services:
    tbn\DoctrineRelationVisualizerBundle\Controller\VisualizerController:
        public: true
        class: 'tbn\DoctrineRelationVisualizerBundle\Controller\VisualizerController'
        arguments:
            - '@tbn\DoctrineRelationVisualizerBundle\Services\EntityService'
            - '%doctrine.default_entity_manager%'
            - '%doctrine.entity_managers%'
            - '%tbn.entity_relation_visualizer.display_columns%'
            - '%tbn.entity_relation_visualizer.area_width%'
            - '%tbn.entity_relation_visualizer.area_height%'
        calls:
            - [setContainer, ['@service_container']]
    tbn\DoctrineRelationVisualizerBundle\Services\EntityService:
        public: true
        class: 'tbn\DoctrineRelationVisualizerBundle\Services\EntityService'
        arguments:
            - '%tbn.entity_relation_visualizer.position_filepath%'
            - '@get_set_foreign_normalizer'
            - '@doctrine'
