services:
    tbn\DoctrineRelationVisualizerBundle\Controller\VisualizerController:
        public: true
        class: "tbn\\DoctrineRelationVisualizerBundle\\Controller\\VisualizerController"
    tbn\DoctrineRelationVisualizerBundle\Services\EntityService:
        public: true
        class: "tbn\\DoctrineRelationVisualizerBundle\\Services\\EntityService"
        arguments:
            - "%tbn.entity_relation_visualizer.position_filepath%"
            - "@get_set_foreign_normalizer"
            - "@doctrine"
