services:
    tbn.entity_relation_visualizer.entity_service:
        class: "tbn\\DoctrineRelationVisualizerBundle\\Services\\EntityService"
        arguments:
            - "%tbn.entity_relation_visualizer.position_filepath%"
            - "@tbn.entity_relation_visualizer.get_set_foreign_normalizer"
            - "@doctrine"

    tbn.entity_relation_visualizer.get_set_foreign_normalizer:
        class: tbn\GetSetForeignNormalizerBundle\Component\Serializer\Normalizer\GetSetPrimaryMethodNormalizer
        arguments: ["@doctrine"]