services:
    tbn.entity_relation_visualizer.entity_service:
        class: "tbn\\DoctrineRelationVisualizerBundle\\Services\\EntityService"
        arguments:
            - "%tbn.entity_relation_visualizer.position_filepath%"
            - "@get_set_foreign_normalizer"
            - "@doctrine"
